train_path: ../Data/CSL_lobby_side_0/raw
test_path: ../Data/CSL_lobby_700/raw
n_layers: 2
try_gpu: True
downsample: .25
lr: .001
schedule_step: 30000
schedule_multiplier: .1
patch_height: 80
patch_width: 80
seed: 0
seq_len: 50

# Radar params will only be read in train_radar.py and test_radar.py

# radar_inclusion_type options: 'in' 'before', 'after'
radar_inclusion_type: 'after'

# set to zero to get rid of cosine multiplier
cosine_multiplier: 0

# Unet
thresh: .075